title: Young Architects Foundation
title-abbreviation: Y A F
subtitle: A professional, social, and urban space
email: archiyclub@gmail.com
copyright-year: 2025

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

collections:
  team_members:

sass:
  quiet_deps: true

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
