baseurl: /archi-site
url: https://spookto.github.io

title: Young Architects Foundation
title-abbreviation: Y A F
subtitle: A collaborative space for urban engagement, civic, and professional growth
email: archiyclub@gmail.com
copyright-year: 2025

paginate: 6
paginate_path: "/articles/:num/"
page_text_next: ">"
page_text_prev: "<"
page_max_buttons_per_dir: 2

defaults:
  -
    scope:
      path: "assets/"
    values:
      image: true
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /articles/:title
      layout: "post"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "post"

collections:
  team_members:
  mentions:
  partners:
  authors:
  events:
    output: true
    permalink: /events/:title

sass:
  quiet_deps: true

plugins:
  - "jekyll-github-metadata"

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
